export { Navbar } from './navbar';
export { Hero } from './hero';
export { LogoCloud } from './logo-cloud';
export { Features } from './features';
export { Comparison } from './comparison';
export { Testimonials } from './testimonials';
export { Pricing } from './pricing';
export { CTA } from './cta';
export { Footer } from './footer';
